const locators = {
    LOGIN: {
        INPUT_EMAIL: 'vrc-input.inputMail',
        INPUT_SENHA: 'vrc-input.inputSenha',
        SWITCH_LEMBRAR_USUARIO: '.lever',
        BTN_ENTRAR: '.btn__login'
    },
    BARRA_BUSCA: 'vr-search',
    OPERACAO: {
        CADASTRO: {
            PESSOA: {
                SELECT_ITEM: item => `div.select2-label-content:contains('${item}')`,

                CONSULTA_BTN_VOLTAR: 'vr-nav-button-back',
                CONSULTA_BTN_CADASTRAR: 'vr-nav-button-add',
                CONSULTA_INPUT_CODIGO: '#id',
                CONSULTA_INPUT_NOME: '#nomeRazaoSocial',
                CONSULTA_INPUT_CPFCNPJ: '#cnpjCpf',
                CONSULTA_SELECT_TIPO_INSCRICAO: '#tipoInscricao',
                CONSULTA_SELECT_TIPO_PESSOA: '#tipoPessoa',
                CONSULTA_SELECT_SITUACAO: '#situacao',
                CONSULTA_DATATABLE_ROW: conteudo => `datatable-body-row:contains('${conteudo}')`,
                CONSULTA_DATATABLE_CHECKBOX: '.checkbox__label',
                CONSULTA_DATATABLE_EDITAR: '.vr-editar',
                CONSULTA_DATATABLE_SLIDE_SITUACAO: '.lever',
                CONSULTA_DATATABLE_ITENS_PAGINA: 'datatable-footer select',
                CONSULTA_DATATABLE_NUMERO_PAGINA: numero => `.pages:contains(${numero})`,

                CADASTRO_BTN_VOLTAR: 'vr-nav-button-back',
                CADASTRO_BTN_HISTORICO: 'vr-nav-button-history',
                CADASTRO_BTN_CANCELAR: 'vr-nav-button-cancel button',
                CADASTRO_BTN_SALVAR_NOVO: 'vr-nav-button-save-and-add button',
                CADASTRO_BTN_SALVAR: 'vr-nav-button-save button',
                CADASTRO_MODAL_SAIR_BTN_SEM_SALVAR: '.modal__options .btn__outline--secondary',
                CADASTRO_MODAL_SAIR_BTN_SALVAR: '.btn--primary.btn--not-icon',

                CADASTRO_ABA_DADOS: 'button:contains("Dados")',
                CADASTRO_ABA_DADOS_CODIGO: '[formcontrolname="id"] input',
                CADASTRO_ABA_DADOS_CHECKBOX_SITUACAO: '[formcontrolname="ativo"] .checkbox__label',
                CADASTRO_ABA_DADOS_DATA_CADASTRO: '[formcontrolname="dataCadastro"] input',
                CADASTRO_ABA_DADOS_RADIOBTN_PESSOA_FISICA: '[formcontrolname="tipoInscricao"] span:contains("Pessoa Física"):eq(0)',
                CADASTRO_ABA_DADOS_RADIOBTN_PESSOA_JURIDICA: '[formcontrolname="tipoInscricao"] span:contains("Pessoa Jurídica")',
                CADASTRO_ABA_DADOS_PESSOA_FISICA_NOME: '[formcontrolname="nome"] input',
                CADASTRO_ABA_DADOS_PESSOA_FISICA_CPF: '[formcontrolname="cpf"] input',
                CADASTRO_ABA_DADOS_PESSOA_FISICA_SELECT_TIPO_CONTRIBUINTE: 'vrc-select .selection span:contains("Não Contribuinte")',
                CADASTRO_ABA_DADOS_PESSOA_FISICA_RG: '[formcontrolname="rg"] input',
                CADASTRO_ABA_DADOS_PESSOA_FISICA_DATEPICKER_DATA_NASACIMENTO: '[formcontrolname="dataNascimento"] input',
                CADASTRO_ABA_DADOS_PESSOA_FISICA_SELECT_GENERO: '[formcontrolname="tipoGenero"] .selection',

                CADASTRO_ABA_TIPO_PESSOA: 'button:contains("Tipos de Pessoa")',
                CADASTRO_ABA_TIPO_PESSOA_BTN_ADICIONAR: 'vr-action-list-pessoa .vr-circulo_mais',
                CADASTRO_ABA_TIPO_PESSOA_MODAL_SELECT_TIPO_PESSOA: '[formcontrolname="tipoPessoa"] .selection',
                CADASTRO_ABA_TIPO_PESSOA_MODAL_BTN_CANCELAR: '.modal__options .btn__outline--secondary',
                CADASTRO_ABA_TIPO_PESSOA_MODAL_BTN_SALVAR_NOVO: '.modal__options .btn__outline--primary',
                CADASTRO_ABA_TIPO_PESSOA_MODAL_BTN_SALVAR: '.modal__options .btn--primary',
                CADASTRO_ABA_TIPO_PESSOA_LISTA_TIPO_PESSOA: tipo => `vr-action-list-pessoa .action-list__itens:contains('${tipo}')`,
                CADASTRO_ABA_TIPO_PESSOA_LISTA_TIPO_PESSOA_FECHAR: '.vr-fechar',
                CADASTRO_ABA_TIPO_PESSOA_MODAL_REMOVER_TIPO_PESSOA_BTN_CANCELAR: '.modal__options .btn__outline--secondary',
                CADASTRO_ABA_TIPO_PESSOA_MODAL_REMOVER_TIPO_PESSOA_BTN_CONFIRMAR: '.modal__options .btn--primary',

                CADASTRO_ABA_ENDERECOS: 'button:contains("Endereços")',
                CADASTRO_ABA_ENDERECOS_BTN_ADICIONAR: 'vr-action-table-endereco .vr-circulo_mais',
                CADASTRO_ABA_ENDERECOS_MODAL_TIPO_ENDERECO: '[formcontrolname="idTipoEndereco"] .selection',
                CADASTRO_ABA_ENDERECOS_MODAL_INPUT_DESCRICAO: '[formcontrolname="descricao"] input',
                CADASTRO_ABA_ENDERECOS_MODAL_INPUT_CEP: '[formcontrolname="cep"] input',
                CADASTRO_ABA_ENDERECOS_MODAL_BTN_BUSCA_LOCALIZACAO: '.vr-busca-localizacao',
                CADASTRO_ABA_ENDERECOS_MODAL_INPUT_ENDERECO: '[formcontrolname="endereco"] input',
                CADASTRO_ABA_ENDERECOS_MODAL_INPUT_BAIRRO: '[formcontrolname="bairro"] input',
                CADASTRO_ABA_ENDERECOS_MODAL_INPUT_NUMERO: '[formcontrolname="num"] input',
                CADASTRO_ABA_ENDERECOS_MODAL_SELECT_UF: '[formcontrolname="uf"] .selection',
                CADASTRO_ABA_ENDERECOS_MODAL_SELECT_MUNICIPIO: '[formcontrolname="codMunicipio"] .selection',
                CADASTRO_ABA_ENDERECOS_MODAL_SELECT_PAIS: '[formcontrolname="codPais"] .selection',
                CADASTRO_ABA_ENDERECOS_MODAL_INPUT_COMPLEMENTO: '[formcontrolname="complemento"] input',
                CADASTRO_ABA_ENDERECOS_MODAL_BTN_CANCELAR: '.modal__options .btn__outline--secondary',
                CADASTRO_ABA_ENDERECOS_MODAL_BTN_SALVAR_NOVO: '.modal__options .btn__outline--primary',
                CADASTRO_ABA_ENDERECOS_MODAL_BTN_SALVAR: '.modal__options .btn--primary',
                CADASTRO_ABA_ENDERECOS_DATATABLE_ENDERECO: conteudo => `table-body:contains('${conteudo}')`,
                CADASTRO_ABA_ENDERECOS_DATATABLE_EDITAR: '.vr-editar',
                CADASTRO_ABA_ENDERECOS_DATATABLE_EDITAR: '.vr-fechar',

                CADASTRO_ABA_CONTATOS: 'button:contains("Contatos")',
                CADASTRO_ABA_CONTATOS_BTN_ADICIONAR: 'vr-action-table-contato .vr-circulo_mais',
                CADASTRO_ABA_CONTATOS_MODAL_SELECT_TIPO_CONTATO: '[formcontrolname="idTipoContato"] .selection',
                CADASTRO_ABA_CONTATOS_MODAL_INPUT_CONTATO: '[formcontrolname="contato"] input',
                CADASTRO_ABA_CONTATOS_MODAL_INPUT_TELEFONE: '[formcontrolname="telefone"] input',
                CADASTRO_ABA_CONTATOS_MODAL_INPUT_CELULAR: '[formcontrolname="celular"] input',
                CADASTRO_ABA_CONTATOS_MODAL_INPUT_EMAIL: '[formcontrolname="email"] input',
                CADASTRO_ABA_CONTATOS_MODAL_BTN_CANCELAR: '.modal__options .btn__outline--secondary',
                CADASTRO_ABA_CONTATOS_MODAL_BTN_SALVAR_NOVO: '.modal__options .btn__outline--primary',
                CADASTRO_ABA_CONTATOS_MODAL_BTN_SALVAR: '.modal__options .btn--primary',
                CADASTRO_ABA_CONTATOS_DATATABLE_ENDERECO: conteudo => `table-body:contains('${conteudo}')`,
                CADASTRO_ABA_CONTATOS_DATATABLE_EDITAR: '.vr-editar',
                CADASTRO_ABA_CONTATOS_DATATABLE_EDITAR: '.vr-fechar',

                CADASTRO_ABA_CLIENTE: 'button:contains("Cliente")',
                CADASTRO_ABA_CLIENTE_ABA_DADOS_GERAIS:'button:contains("Dados Gerais")',
                CADASTRO_ABA_CLIENTE_ABA_DADOS_GERAIS_SELECT_CONSUMIDOR_FINAL: '[formcontrolname="codConsumidorFinal"] .selection',
                CADASTRO_ABA_CLIENTE_ABA_DADOS_GERAIS_SELECT_ORGAO_PUBLICO: '[formcontrolname="orgaoPublico"] .selection',
                CADASTRO_ABA_CLIENTE_ABA_DADOS_GERAIS_SELECT_ORGAO_PUBLICO_LI: conteudo => `div.select2-dropdown li:contains('${conteudo}')`,
                CADASTRO_ABA_CLIENTE_ABA_DADOS_GERAIS_SELECT_CLASSE_RISCO: '[formcontrolname="classeRisco"] .selection',
            },
            PRODUTO: {
                SELECT_ITEM: item => `div.select2-label-content:contains('${item}')`,

                CONSULTA_BTN_VOLTAR: 'vr-nav-button-back',
                CONSULTA_BTN_CADASTRAR: 'vr-nav-button-add',
                CONSULTA_BTN_EXPORTAR_ARQUIVO_BALANCA: 'vr-nav-button-exportar-balanca',
                CONSULTA_BTN_CONFIGURACAO_BALANCA: 'vr-nav-button-configucacao-balanca',
                CONSULTA_BTN_MIGRAR: 'vr-nav-button-migrate',
                CONSULTA_INPUT_CODIGO: '#id',
                CONSULTA_INPUT_DESCRICAO: '#descricaoCompleta',
                CONSULTA_INPUT_CODIGO_BARRAS: '#codigosBarra',
                CONSULTA_SELECT_TIPO_PRODUTO: '#idTipoProduto',
                CONSULTA_SELECT_MARCA: '#idMarca',
                CONSULTA_SELECT_CLASSIFICACAO: '#idClassificacao',
                CONSULTA_SELECT_EMBALAGEM: '#embalagem',
                CONSULTA_SELECT_SITUACAO: '#situacao',
                CONSULTA_MAIS_FILTRO: '.vr-mais',
                CONSULTA_DATATABLE_ROW: conteudo => `datatable-body-row:contains('${conteudo}')`,
                CONSULTA_DATATABLE_CHECKBOX: '.checkbox__label',
                CONSULTA_DATATABLE_EDITAR: '.vr-editar',
                CONSULTA_DATATABLE_SLIDE_SITUACAO: '.lever',
                CONSULTA_DATATABLE_ITENS_PAGINA: 'datatable-footer select',
                CONSULTA_DATATABLE_NUMERO_PAGINA: numero => `.pages:contains(${numero})`,

                CADASTRO_BTN_VOLTAR: 'vr-nav-button-back',
                CADASTRO_BTN_HISTORICO: 'vr-nav-button-history',
                CADASTRO_BTN_CANCELAR: 'vr-nav-button-cancel button',
                CADASTRO_BTN_SALVAR_NOVO: 'vr-nav-button-save-and-add button',
                CADASTRO_BTN_SALVAR: 'vr-nav-button-save button',
                CADASTRO_MODAL_SAIR_BTN_SEM_SALVAR: '.modal__options .btn__outline--secondary',
                CADASTRO_MODAL_SAIR_BTN_SALVAR: '.btn--primary.btn--not-icon',

                CADASTRO_MODAL_DEFINICAO_PRECO_PULAR: 'vr-preco-nao-definido-modal .btn--secondary',
                CADASTRO_MODAL_DEFINICAO_PRECO_DEFINIR: 'vr-preco-nao-definido-modal .btn--primary',
                
                CADASTRO_MODAL_ADMINISTRACAO_PRECO_CUSTO_COM_IMPOSTO: '[formcontrolname="custoComImposto"] input',
                CADASTRO_MODAL_ADMINISTRACAO_PRECO_PRECO_COMUM_NOVO: '[formcontrolname="precoNovo"] input',
                CADASTRO_MODAL_ADMINISTRACAO_PRECO_PULAR: 'vr-administracao-preco-modal .btn--secondary',
                CADASTRO_MODAL_ADMINISTRACAO_PRECO_DEFINIR: 'vr-administracao-preco-modal .btn--primary',

                CADASTRO_ABA_DADOS_GERAIS_CODIGO: '[formcontrolname="id"] input',
                CADASTRO_ABA_DADOS_GERAIS_CHECKBOX_SITUACAO: '[formcontrolname="ativo"] .checkbox__label',
                CADASTRO_ABA_DADOS_GERAIS_DESCRICAO: '[formcontrolname="descricaoCompleta"] input',
                CADASTRO_ABA_DADOS_GERAIS_INPUT_DESCRICAO_CUPOM: '[formcontrolname="descricaoCupom"] input',
                CADASTRO_ABA_DADOS_GERAIS_INPUT_DESCRICAO_GONDOLA: '[formcontrolname="descricaoGondola"] input',
                CADASTRO_ABA_DADOS_GERAIS_SELECT_TIPO_PRODUTO: '[formcontrolname="tipoProduto"] .selection',
                CADASTRO_ABA_DADOS_GERAIS_TIPO_PRODUTO_PRINCIPAL: '[formcontrolname="tipoProduto"] .vr-principal',
                CADASTRO_ABA_DADOS_GERAIS_SELECT_EMBALAGEM: '[formcontrolname="embalagem"] .selection',
                CADASTRO_ABA_DADOS_GERAIS_INPUT_QTD_EMBALAGEM: '[formcontrolname="qtdEmbalagem"] input',
                CADASTRO_ABA_DADOS_GERAIS_CHECKBOX_PESAVEL: '[formcontrolname="pesavel"] .checkbox__label',
                CADASTRO_ABA_DADOS_GERAIS_SELECT_CLASSIFICACAO_PRODUTO: '[formcontrolname="idClassificacaoProduto"] .selection',
                CADASTRO_ABA_DADOS_GERAIS_SELECT_FAMILIA_PRODUTO: '[formcontrolname="idFamiliaProduto"] .selection',
                CADASTRO_ABA_DADOS_GERAIS_SELECT_BUSCA_FAMILIA_PRODUTO: '[formcontrolname="idFamiliaProduto"] input',
                CADASTRO_ABA_DADOS_GERAIS_SELECT_MARCA: '[formcontrolname="idMarca"] .selection',
                CADASTRO_ABA_DADOS_GERAIS_SELECT_BUSCA_MARCA: '[formcontrolname="idMarca"] input',

                CADASTRO_ABA_FISCAL: 'button:contains("Fiscal")',
                CADASTRO_ABA_FISCAL_NCM: '[formcontrolname="idNCM"] .selection',
                CADASTRO_ABA_FISCAL_BUSCA_NCM: '[formcontrolname="idNCM"] input',
                CADASTRO_ABA_FISCAL_NCM_LI: conteudo => `div.select2-dropdown li:contains('${conteudo}')`,
                CADASTRO_ABA_FISCAL_ORIGEM_MERCADORIA: '[formcontrolname="idOrigemMercadoria"] .selection',
                CADASTRO_ABA_FISCAL_BUSCA_ORIGEM_MERCADORIA: '[formcontrolname="idOrigemMercadoria"] input',
                CADASTRO_ABA_FISCAL_BTN_ADICIONAR_CENARIO_FISCAL: 'vr-action-table-cenario-fiscal .vr-circulo_mais',
                CADASTRO_ABA_FISCAL_MODAL_CENARIO_FISCAL_CODIGO: 'vr-cenario-fiscal-modal #id',
                CADASTRO_ABA_FISCAL_MODAL_CENARIO_FISCAL_DESCRICAO: 'vr-cenario-fiscal-modal #descricao',
                CADASTRO_ABA_FISCAL_MODAL_CENARIO_FISCAL_DATATABLE_ROW: conteudo =>  `datatable-body-row:contains('${conteudo}')`,
                CADASTRO_ABA_FISCAL_MODAL_CENARIO_FISCAL_CHECKBOX_ROW: '.checkbox__label',
                CADASTRO_ABA_FISCAL_MODAL_CENARIO_FISCAL_CANCELAR: 'vr-cenario-fiscal-modal .btn--secondary',
                CADASTRO_ABA_FISCAL_MODAL_CENARIO_FISCAL_CARREGAR: 'vr-cenario-fiscal-modal .btn--primary'
            }
        }
    },
    VENDA: {
        PEDIDO_DE_VENDA: {
            SELECT_ITEM: item => `div.select2-label-content:contains('${item}')`,

            CONSULTA_BTN_VOLTAR: 'vr-nav-button-back',
            CONSULTA_BTN_CADASTRAR: 'vr-nav-button-add',
            CONSULTA_BTN_FINALIZAR: 'vr-nav-button-finalize',
            CONSULTA_BTN_ESTORNAR: 'vr-nav-button-reversal',
            CONSULTA_BTN_CANCELAR: 'vr-nav-button-cancel-item',
            CONSULTA_INPUT_CODIGO: '#id',
            CONSULTA_SELECT_LOJA: '#idLoja',
            CONSULTA_DATEPICKER_INICIO_LANCAMENTO: 'vrc-datepicker:contains("Data Lançamento") .start-date',
            CONSULTA_DATEPICKER_TERMINO_LANCAMENTO: 'vrc-datepicker:contains("Data Lançamento") .end-date',
            CONSULTA_DATEPICKER_INICIO_LANCAMENTO: 'vrc-datepicker:contains("Data Emissão") .start-date',
            CONSULTA_DATEPICKER_TERMINO_LANCAMENTO: 'vrc-datepicker:contains("Data Emissão") .end-date',
            CONSULTA_SELECT_TIPO_PEDIDO: '#tipoPedido',
            CONSULTA_SELECT_SITUACAO: '#situacaoPedido',
            CONSULTA_SELECT_PESSOA: '#idPessoaCliente',
            CONSULTA_DATATABLE_ROW: conteudo => `datatable-body-row:contains('${conteudo}')`,
            CONSULTA_DATATABLE_CHECKBOX: '.checkbox__label',
            CONSULTA_DATATABLE_EDITAR: '.vr-editar',
            CONSULTA_DATATABLE_ITENS_PAGINA: 'datatable-footer select',
            CONSULTA_DATATABLE_NUMERO_PAGINA: numero => `.pages:contains(${numero})`,

            CADASTRO_BTN_VOLTAR: 'vr-nav-button-back',
            CADASTRO_BTN_CANCELAR: 'vr-nav-button-cancel button',
            CADASTRO_BTN_SALVAR_NOVO: 'vr-nav-button-save-and-add button',
            CADASTRO_BTN_SALVAR: 'vr-nav-button-save button',
            CADASTRO_MODAL_SAIR_BTN_SEM_SALVAR: '.modal__options .btn__outline--secondary',
            CADASTRO_MODAL_SAIR_BTN_SALVAR: '.btn--primary.btn--not-icon',
            CADASTRO_INPUT_NUMERO_VENDA: '[formcontrolname="id"] input',
            CADASTRO_SELECT_LOJA: '[formcontrolname="idLoja"] [role="combobox"]',
            CADASTRO_DATEPICKER_DATA_LANCAMENTO: '[formcontrolname="dataLancamento"] input',
            CADASTRO_DATEPICKER_DATA_EMISSAO: '[formcontrolname="dataEmissao"] input',
            CADASTRO_SELECT_CLIENTE: '[formcontrolname="idPessoaCliente"] [role="combobox"]',
            CADASTRO_SELECT_BUSCA_CLIENTE: '[formcontrolname="idPessoaCliente"] .input_search',
            CADASTRO_CLIENTE_LUPA: 'vrc-select[formcontrolname="idPessoaCliente"] vrc-icon',
            CADASTRO_MODAL_CLIENTE_INPUT_CODIGO: '#id',
            CADASTRO_MODAL_CLIENTE_INPUT_NOME: '#nomeRazaoSocial',
            CADASTRO_MODAL_CLIENTE_INPUT_CPFCNPJ: '#cnpjCpf',
            CADASTRO_MODAL_CLIENTE_SELECT_SITUACAO: '#situacao',
            CADASTRO_MODAL_CLIENTE_DATATABLE_ROW: conteudo => `datatable-body-row:contains('${conteudo}')`,
            CADASTRO_MODAL_CLIENTE_DATATABLE_NUMERO_PAGINA: numero => `.pages:contains(${numero})`,
            CADASTRO_MODAL_CLIENTE_BTN_CANCELAR: '.modal .btn--secondary',
            CADASTRO_MODAL_CLIENTE_BTN_SELECIONAR: '.modal .btn--primary',
            CADASTRO_SELECT_ENDERECO: '[formcontrolname="idEndereco"] [role="combobox"]',
            CADASTRO_SELECT_CONTATO: '[formcontrolname="idContato"] [role="combobox"]',
            CADASTRO_SELECT_TIPO_PEDIDO: '[formcontrolname="tipoPedido"] .selection',
            CADASTRO_SELECT_SITUACAO: '[formcontrolname="situacaoPedido"] .selected-text-container',
            CADASTRO_INPUT_OBSERVACAO: '[formcontrolname="observacao"] input',

            CADASTRO_CARD_TOTAL_ITENS: 'vrc-card-value:contains("Total de Itens")',
            CADASTRO_CARD_TOTAL_BRUTO: 'vrc-card-value:contains("Total Bruto")',
            CADASTRO_CARD_ACRESCIMO_TOTAL: 'vrc-card-value:contains("Acréscimo Total")',
            CADASTRO_CARD_DESCONTO_TOTAL: 'vrc-card-value:contains("Desconto Total")',
            CADASTRO_CARD_TOTAL_LIQUIDO: 'vrc-card-value:contains("Total Líquido")',

            CADASTRO_BTN_ADD_PRODUTO: 'vrc-icon .vr-circulo_mais',
            CADASTRO_MODAL_PRODUTO_INPUT_CODIGO: '#id',
            CADASTRO_MODAL_PRODUTO_INPUT_DESCRICAO: '#descricaoCompleta',
            CADASTRO_MODAL_PRODUTO_INPUT_CODIGO_BARRAS: '#codigosBarra',
            CADASTRO_MODAL_PRODUTO_SELECT_TIPO_PRODUTO: '#idTipoProduto',
            CADASTRO_MODAL_PRODUTO_SELECT_BUSCA_TIPO_PRODUTO: '#idTipoProduto #idTipoProduto-search-field',
            CADASTRO_MODAL_PRODUTO_SELECT_MARCA: '#idMarca',
            CADASTRO_MODAL_PRODUTO_SELECT_BUSCA_MARCA: '#idMarca #idMarca-search-field',
            CADASTRO_MODAL_PRODUTO_SELECT_CLASSIFICACAO_PRODUTO: '#idClassificacao',
            CADASTRO_MODAL_PRODUTO_SELECT_BUSCA_CLASSIFICACAO_PRODUTO: '#idClassificacao #idClassificacao-search-field',
            CADASTRO_MODAL_PRODUTO_SELECT_EMBALAGEM: '#embalagem',
            CADASTRO_MODAL_PRODUTO_SELECT_SITUACAO: '#situacao',
            CADASTRO_MODAL_PRODUTO_BTN_MAIS_FILTRO: 'button:contains("Mais")',
            CADASTRO_MODAL_PRODUTO_MAIS_FILTRO_LI: filtro => `li:contains('${filtro}')`,
            CADASTRO_MODAL_PRODUTO_BTN_REMOVER_MAIS_FILTRO: 'vr-filter-form-field .vr-fechar',
            CADASTRO_MODAL_PRODUTO_DATATABLE_ROW: conteudo => `vr-pedido-venda-produto-modal datatable-body-row:contains('${conteudo}')`,
            CADASTRO_MODAL_PRODUTO_DATATABLE_CHECKBOX: '.checkbox__label',
            CADASTRO_MODAL_PRODUTO_DATATABLE_NUMERO_PAGINA: numero => `.pages:contains(${numero})`,
            CADASTRO_MODAL_PRODUTO_BTN_CANCELAR: '.modal .btn--secondary',
            CADASTRO_MODAL_PRODUTO_BTN_CARREGAR: '.actions-align .btn--primary',
            CADASTRO_DATATABLE_CHECKBOX: '.checkbox__label',
            CADASTRO_DATATABLE_INPUT_QTD_PRODUTO: '[formcontrolname="quantidade"] input',
            CADASTRO_DATATABLE_INPUT_DESCONTO_PRODUTO: '[formcontrolmonetario="descontoMonetario"] vrc-input',
            CADASTRO_DATATABLE_BTN_DESCONTO_MONETARIO_PRODUTO: '[formcontrolmonetario="descontoMonetario"] .no-selected',
            CADASTRO_DATATABLE_BTN_DESCONTO_PERCENTUAL_PRODUTO: '[formcontrolmonetario="descontoMonetario"] .selected',
            CADASTRO_DATATABLE_INPUT_ACRESCIMO_PRODUTO: '[formcontrolmonetario="acrescimoMonetario"] vrc-input',
            CADASTRO_DATATABLE_BTN_ACRESCIMO_MONETARIO_PRODUTO: '[formcontrolmonetario="acrescimoMonetario"] .no-selected',
            CADASTRO_DATATABLE_BTN_ACRESCIMO_PERCENTUAL_PRODUTO: '[formcontrolmonetario="acrescimoMonetario"] .selected',
            CADASTRO_DATATABLE_INPUT_OBSERVACAO_PRODUTO: 'vrc-datatable vrc-input[formcontrolname="observacao"]',
            CADASTRO_DATATABLE_BTN_EXCLUIR_PRODUTO: '.btn--fire-event',
            CADASTRO_DATATABLE_BTN_CANCELAR_PRODUTO: 'btn--fire-event-cancel',

            CADASTRO_EXPORT_FILE_BTN_EXPORTAR_TABELA: '.vr-exportar_tabela',
            CADASTRO_EXPORT_FILE_RADIO: '#radio-relatorio',
            CADASTRO_EXPORT_FILE_RADIO: '#radio-excel',
            CADASTRO_EXPORT_FILE_RADIO: '#radio-arquivo',
            CADASTRO_EXPORT_FILE_BTN__APLICAR: '.datatable-tool-btn',
            CADASTRO_MODAL_EXPORT_FILE_TODAS_COLUNAS: 'thead th:eq(0)',
            CADASTRO_MODAL_EXPORT_FILE_BTN_GERAR: 'datatable-file-config button'
        }
    }
}


export default locators;